version: '3.1'

services:

  # Access postgres DB with adminer on http://localhost:8080
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backstage:
    build:
      context: ../../app
      dockerfile: packages/backend/dev.dockerfile
    restart: always
    ports:
      - 7007:7007
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: backstage
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: backstage
